waFlim/Controllers/ChitietphimController.cs
using Microsoft.AspNetCore.Mvc;

namespace waFlim.Controllers
{
    public class ChitietphimController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

waFlim/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using waFlim.Models;

namespace waFlim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

waFlim/Controllers/PhimboController.cs
using Microsoft.AspNetCore.Mvc;

namespace waFlim.Controllers
{
    public class PhimboController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

waFlim/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="image-slide">
    <button class="pre">
        <i class="fa-solid fa-chevron-left"></i>
    </button>
    <img src="https://www.koimoi.com/wp-content/new-galleries/2022/03/the-batman-does-have-a-post-credit-scene-heres-how-you-can-watch-it-001.jpg" />
    <button class="next">
        <i class="fa-solid fa-chevron-right"></i>
    </button>
</div>

<div class="Action-Film">
    <a asp-controller="" asp-action="" class="title-action">Phim boom tan</a>
    <div class="slide-movie">
        <i class="fa-solid fa-chevron-left"></i>
        <div class="list-movie">
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <a class="name-movie" asp-controller="Chitietphim" asp-action="index">Black Adam</a>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <a class="name-movie" asp-controller="Home" asp-action="index">Black Adam</a>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <a class="name-movie" asp-controller="Home" asp-action="index">Black Adam</a>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <a class="name-movie" asp-controller="Home" asp-action="index">Black Adam</a>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <a class="name-movie" asp-controller="Home" asp-action="index">Black Adam</a>
            </div>
        </div>
        <i class="fa-solid fa-chevron-right"></i>
    </div>
</div>

<div class="Action-Film">
    <a asp-controller="Phimbo" asp-action="Index" class="title-action">Phim bộ</a>
    <div class="slide-movie">
        <i class="fa-solid fa-chevron-left"></i>
        <div class="list-movie">
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <p class="name-movie">Black Adam</p>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <p class="name-movie">Black Adam</p>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <p class="name-movie">Black Adam</p>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <p class="name-movie">Black Adam</p>
            </div>
            <div class="movie">
                <img src="https://m.media-amazon.com/images/I/61TIuVrWBvL.jpg" />
                <p class="name-movie">Black Adam</p>
            </div>
        </div>
        <i class="fa-solid fa-chevron-right"></i>
    </div>
</div>