waFlim/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace waFlim.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

waFlim/Controllers/PhimboController.cs
using Microsoft.AspNetCore.Mvc;

namespace waFlim.Controllers
{
    public class PhimboController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

waFlim/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace waFlim.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

waFlim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - waFlim</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>
    @* header *@
    <div class="header">
        <div class="img-form">
            <img src="~/img/logo.png" />
        </div>
        <div class="list-menu">
            <ul>
                <li><a asp-controller="Home" asp-action="index">Trang chu</a></li>
                <li><a asp-controller="Phimbo" asp-action="Index">Phim bộ</a></li>
                <li><a href="">Phim lẻ</a></li>
                <li><a asp-controller="Search" asp-action="Index"><i class="fa-solid fa-magnifying-glass"></i></a></li>
            </ul>
        </div>
        <div class="button">
            <button><a asp-controller="Login" asp-action="Index">Dang nhap</a></button>
        </div>
    </div>
    @* body *@
    <div class="body">
        @RenderBody()
    </div>
    @* footer *@
    <div class="footer">
        <div class="policy">
            <ul>
                <li>Chính Sách</li>
                <li>Về chúng tôi</li>
                <li>Bảo hành</li>
                <li>Ưu đãi</li>
                <li>Liên hệ</li>
            </ul>
        </div>
        <div class="social">
            <img src="./img/fbico.png" />
            <img src="./img/icoytb.png" />
            <img src="./img/icointergam.png" />
        </div>
        <div class="coppyright">copyright-DoAnChuyenNganh-2023</div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>